### ISSUE TITLE
Prepare email content

### ISSUE THREAD

**Issue by schlessera** [wp-core-php/servehappy#40] opened 2019-03-04 16:14 UTC
We need the content for the email we send to a site administrator on error to provide them with the recovery link.

**Comment by schlessera** [comment] 2019-03-04 16:14
Template currently in use as provided by @TimothyBJacobs:
```
Howdy,

Your site recently crashed on TBD and may not be working as expected.

This may be caused by the Test Plugin plugin.

Click the link below to initiate recovery mode to fix the problem.

This link expires in 4 hours.

http://trunk.test/wp-login.php?action=enter_recovery_mode&rm_key=fP5I3U7cp76Xq8iyVh0A 

Error Details
=============
An error of type E_ERROR in line 22 of the file /app/public/src/wp-content/plugins/test-plugin/test-plugin.php. 
Error message: Uncaught Exception in /app/public/src/wp-content/plugins/test-plugin/test-plugin.php:22
Stack trace:
#0 /app/public/src/wp-includes/class-wp-hook.php(286): {closure}('')
#1 /app/public/src/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /app/public/src/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /app/public/src/wp-settings.php(386): do_action('plugins_loaded')
#4 /app/public/wp-config.php(83): require_once('/app/public/src...')
#5 /app/public/src/wp-load.php(42): require_once('/app/public/wp-...')
#6 /app/public/src/wp-admin/admin.php(34): require_once('/app/public/src...')
#7 /app/public/src/wp-admin/plugins.php(10): require_once('/app/public/src...')
#8 {main}
  thrown
```

**Comment by schlessera** [comment] 2019-03-04 16:16
Related to PR: https://github.com/wp-core-php/wordpress-develop/pull/6

**Comment by afragen** [comment] 2019-03-18 16:56
@TimothyBJacobs is this the current copy, data, link??, etc?

**Comment by TimothyBJacobs** [comment] 2019-03-18 16:56
Yes all up to date.

**Comment by missjwo** [comment] 2019-03-18 17:15
Highlighted suggestions in bold. 

Can I also just make it clear the `Howdy` makes me cringe. I'm wondering if we're going to have translated versions of the email?

I realise the `Thank You, WordPress.org` might be overkill. Take it as you wish. 

---

Howdy,

Your site **<a href="http://trunk.test">trunk.test</a>**, recently crashed **at** TBD and may not be working as expected.

This may be caused by the Test Plugin plugin.

Please click the link below to initiate recovery mode to fix the problem.

This link expires in 4 hours.

http://trunk.test/wp-login.php?action=enter_recovery_mode&rm_key=fP5I3U7cp76Xq8iyVh0A 

**Thank you**

**WordPress.org**

----

**## For technical reference:** 
```
Error Details
=============
An error of type E_ERROR in line 22 of the file /app/public/src/wp-content/plugins/test-plugin/test-plugin.php. 
Error message: Uncaught Exception in /app/public/src/wp-content/plugins/test-plugin/test-plugin.php:22
Stack trace:
#0 /app/public/src/wp-includes/class-wp-hook.php(286): {closure}('')
#1 /app/public/src/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /app/public/src/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /app/public/src/wp-settings.php(386): do_action('plugins_loaded')
#4 /app/public/wp-config.php(83): require_once('/app/public/src...')
#5 /app/public/src/wp-load.php(42): require_once('/app/public/wp-...')
#6 /app/public/src/wp-admin/admin.php(34): require_once('/app/public/src...')
#7 /app/public/src/wp-admin/plugins.php(10): require_once('/app/public/src...')
#8 {main}
  thrown
```

**Comment by missjwo** [comment] 2019-03-18 17:19
I would also suggest the TBD includes the time as well as the date.

**Comment by TimothyBJacobs** [comment] 2019-03-18 19:59
One of the things TBD could include is the page that the error occurred on, for instance

`wp-login.php`
`wp-admin/edit.php?post_type=post`

Do you think that'd be valuable to include?

**Comment by afragen** [comment] 2019-03-18 22:39
I don’t think we need to personify the email with “Howdy” or “Thank you”. 

I don’t think a timestamp is needed with the 4 hour information as the email timestamp fulfills this data point. 

Yes, having the page the error occurred on might be helpful.

**Comment by karmatosed** [comment] 2019-03-20 14:17
I think some greeting (doesn't have to be Howdy) and some closing (Thank you is nice), really adds a human level to this I think is needed.

**Comment by TimothyBJacobs** [comment] 2019-04-13 03:31
Resolved in https://core.trac.wordpress.org/changeset/45181

**Closed as completed by TimothyBJacobs** 2019-04-13 03:31 UTC
